### ISSUE TITLE
TODO-MVC2

### ISSUE THREAD

**Issue by wizaster** [wizaster/php_room_rental#11]
- [x] modularize views
- [x] front controller
- [x] controller : log in
- [x] controller : sign up
- [x] controller : search room
- [x] controller : add a room
- [ ] controller : rent a room
- [ ] controller : admin add stuff
- [ ] controller : admin remove stuff
- [x] controller : show all room
- [x] controller : show one room
- [ ] controller : add an event
