### ISSUE TITLE
TODO - pages

### ISSUE THREAD

**Issue by wizaster** [wizaster/php_room_rental#8]
- [ ] search engine
- [x] log in
- [x] add option to room
- [ ] add map
- [x] class and DAO for all tables
- [x] write DAO class
- [x] wrtie loadfromarray and loadfromobject methods
- [ ] rent a room
- [ ] show listings
- [ ] show one room
- [ ] add images
